version: "3"

services:
  web:
    build:
      context: ./app
    ports:
      - 5200:5200
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    command: npm start

  redis:
    image: redis:latest
    ports: 
      - 6379:6379
    volumes:
      - ./data/redis:/data
